---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: liblog
  labels:
    app: mysql
data:
  my.cnf: |-
    [client]
    default-character-set=utf8mb4
    [mysqld]
    port=3306
    innodb_buffer_pool_size=4G
    log-error=error.log
    max_connections=1000
    binlog_format=row
    innodb_log_file_size=102400000
    join_buffer_size=128m
    sort_buffer_size=4m
    key_buffer_size = 15M
    read_buffer_size = 8M
    bulk_insert_buffer_size = 64M
    innodb_buffer_pool_load_at_startup = 1
    innodb_write_io_threads = 8
    innodb_read_io_threads = 8
    innodb_purge_threads = 4
    innodb_page_cleaners = 4
    innodb_open_files = 65535
    innodb_max_dirty_pages_pct = 50
    innodb_flush_method = O_DIRECT
    innodb_lru_scan_depth = 4000
    innodb_checksum_algorithm = crc32
    read_rnd_buffer_size=4m
    skip-name-resolve
    character-set-client-handshake=false
    slave_skip_errors=ddl_exist_errors
    init_connect='SET NAMES utf8mb4'
    explicit_defaults_for_timestamp = true
    table_open_cache = 600
    tmp_table_size = 64M
    max_heap_table_size = 64M
    log_timestamps = SYSTEM
    binlog_cache_size = 4M
    max_binlog_cache_size = 2G
    max_binlog_size = 1G
    general_log=0
    transaction_isolation = READ-COMMITTED
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci
    default_authentication_plugin=mysql_native_password
    gtid-mode=on
    enforce-gtid-consistency=on
    log-slave-updates=on
    #解决 ONLY_FULL_GROUP_BY 问题
    sql_mode =STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    [mysqldump]
    quick
    max_allowed_packet = 128M

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-nodeport-svc
  namespace: liblog
spec:
  type: NodePort
  ports:
    - name: mysql-nodeport
      port: 3306
      nodePort: 57001
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: liblog
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  clusterIP: "None"
  ports:
  - name: mysql-svc-3306
    port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql-master
  namespace: liblog
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: shinemo123
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: shinemo123
          image: mysql:8.0.26
          name: mysql-container
          ports:
            - containerPort: 3306
              name: dbapi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
            - name: config
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
          resources:
            limits:
              cpu: "2"
              memory: 1024Mi
            requests:
              cpu: "1"
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: mysql-config
      securityContext:
       runAsUser: 999
       fsGroup: 999
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "new-nfs-storage"
      resources:
        requests:
          storage: 40Gi

